# Generated by Django 5.2 on 2025-04-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Equipamento')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de Equipamento')),
                ('validade', models.DateField(verbose_name='Data de Validade')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade Disponível')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
    ]
