# Generated by Django 5.2 on 2025-04-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0002_equipamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='validade',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='numero_serie',
            field=models.CharField(default='DEFAULT123', max_length=100),
        ),
    ]
