# Generated by Django 5.2 on 2025-04-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0003_remove_equipamento_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='fabricante',
            field=models.CharField(default='DEFAULT123', max_length=100),
        ),
    ]
