# Generated by Django 5.1.6 on 2025-04-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_trabalho', '0005_alter_equipamento_options_remove_colaborador_cargo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'verbose_name': 'Equipamento', 'verbose_name_plural': 'Equipamentos'},
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(default='Sem cargo', max_length=50),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(default='sem_email@exemplo.com', max_length=254),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='idade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='telefone',
            field=models.CharField(default='0000-0000', max_length=15),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='fabricante',
            field=models.CharField(default='DEFAULT123', max_length=100),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='numero_serie',
            field=models.CharField(default='DEFAULT123', max_length=100),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(default='Desconhecido', max_length=100, verbose_name='Tipo de Equipamento'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Equipamento'),
        ),
    ]
